version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # 映射宿主机的 5000 端口到容器的 5000 端口
    volumes:
      - ./output:/app/output  # 映射 output 目录，以便持久化 CSV 文件
    environment:
      - FLASK_ENV=development  # 启用 Flask 开发模式（调试）
    restart: unless-stopped  # 容器意外退出时自动重启